### The pivot method
* The **pivot** method reshapes data from a tall format to a wide format.
* Ask yourself which direction the data will expand in if you add more entries.
* A tall/long format expands down. A wide format expands out.
* The **index** parameter sets the horizontal index of the pivoted **DataFrame**.
* The **columns** paramter sets the column whose values will be the columns in the pivoted **DataFrame**.
* The **values** parameter set the values of the pivoted **DataFrame**. Pandas will populate the correct values based on the index and column intersections.

In [1]:
import pandas as pd

In [2]:
dataframe = pd.read_csv("../Crime Prediction in Chicago_Dataset.csv")

In [3]:
dataframe.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,12592454,JF113025,1/14/2022 15:55,067XX S MORGAN ST,2826,OTHER OFFENSE,HARASSMENT BY ELECTRONIC MEANS,RESIDENCE,False,True,...,16.0,68,26,1170805.0,1860170.0,2022,9/14/2023 15:41,41.771782,-87.649437,"(41.771782439, -87.649436929)"
1,12785595,JF346553,08-05-2022 21:00,072XX S UNIVERSITY AVE,1544,SEX OFFENSE,SEXUAL EXPLOITATION OF A CHILD,APARTMENT,True,False,...,5.0,69,17,1185135.0,1857211.0,2022,9/14/2023 15:41,41.763338,-87.597001,"(41.763337967, -87.597001131)"
2,12808281,JF373517,8/14/2022 14:00,055XX W ARDMORE AVE,1562,SEX OFFENSE,AGGRAVATED CRIMINAL SEXUAL ABUSE,RESIDENCE,False,False,...,39.0,11,17,1138383.0,1937953.0,2022,9/14/2023 15:41,41.985875,-87.766404,"(41.985875279, -87.766403857)"
3,12888104,JF469015,11-10-2022 03:47,072XX S MAY ST,1477,WEAPONS VIOLATION,RECKLESS FIREARM DISCHARGE,STREET,False,False,...,17.0,68,15,1169903.0,1856822.0,2022,9/14/2023 15:41,41.762615,-87.652840,"(41.76261474, -87.652840463)"
4,13209277,JG422539,8/15/2022 9:00,0000X W JACKSON BLVD,810,THEFT,OVER $500,COMMERCIAL / BUSINESS OFFICE,False,False,...,4.0,32,6,NaN,NaN,2022,9/14/2023 15:43,NaN,NaN,NaN

In [10]:
df = dataframe.head()

In [11]:
df.pivot(index="ID", columns="Case Number", values="Description")

Case Number,JF113025,JF346553,JF373517,JF469015,JG422539
ID,,,,,
12592454,HARASSMENT BY ELECTRONIC MEANS,NaN,NaN,NaN,NaN
12785595,NaN,SEXUAL EXPLOITATION OF A CHILD,NaN,NaN,NaN
12808281,NaN,NaN,AGGRAVATED CRIMINAL SEXUAL ABUSE,NaN,NaN
12888104,NaN,NaN,NaN,RECKLESS FIREARM DISCHARGE,NaN
13209277,NaN,NaN,NaN,NaN,OVER $500