### The drop_duplicates method
* The **drop_duplicates** method delete rows with duplicate values.
* By default, it will remove a row if all of its values are shared with another row.
* The **subset** parameter configures the columns to look for duplicate values within.
* Pass a list to **subset** parameter to look fr duplicates across multiple columns.

In [1]:
import pandas as pd

In [2]:
dataframe = pd.read_csv("Crime Prediction in Chicago_Dataset.csv")

In [7]:
dataframe.drop_duplicates()

dataframe.drop_duplicates('Primary Type')

dataframe.drop_duplicates('Primary Type', keep="first")

dataframe.drop_duplicates('Primary Type', keep="last")

dataframe.drop_duplicates('Primary Type', keep=False)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
39021,12669127,JF206171,04-12-2022 22:27,011XX N LARRABEE ST,1481,NON-CRIMINAL,CONCEALED CARRY LICENSE REVOCATION,POLICE FACILITY / VEHICLE PARKING LOT,True,False,...,27.0,8,15,1172122.0,1908040.0,2022,01-03-2023 15:40,41.903113,-87.643199,"(41.903113054, -87.643199348)"
44563,12731836,JF281839,6/16/2022 11:22,0000X E 111TH ST,1536,PUBLIC INDECENCY,LICENSED PREMISE,RESTAURANT,True,False,...,9.0,49,17,1178327.0,1831371.0,2022,01-03-2023 15:40,41.692587,-87.622735,"(41.692586937, -87.622735417)"

In [11]:
dataframe.drop_duplicates(["Primary Type", "Location Description"]).sort_values('Primary Type')

dataframe.drop_duplicates(["Primary Type", "Location Description"], keep="last").sort_values('Primary Type')

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
26684,12583120,JF100217,01-01-2022 03:58,090XX S ASHLAND AVE,1020,ARSON,BY FIRE,AUTO / BOAT / RV DEALERSHIP,False,False,...,21.0,73,9,1167254.0,1844859.0,2022,01-03-2023 15:40,41.729844,-87.662891,"(41.729843669, -87.662891098)"
22874,12583157,JF100818,01-01-2022 19:15,003XX W 79TH ST,1020,ARSON,BY FIRE,CTA BUS,False,False,...,17.0,69,9,1175574.0,1852569.0,2022,01-03-2023 15:40,41.750819,-87.632182,"(41.750819013, -87.632182489)"
31756,12622813,JF150257,2/20/2022 9:37,008XX W WELLINGTON AVE,1090,ARSON,ATTEMPT ARSON,HOSPITAL BUILDING / GROUNDS,True,False,...,44.0,6,9,1169981.0,1920130.0,2022,01-03-2023 15:40,41.936336,-87.650710,"(41.936335635, -87.650710119)"
2511,12744064,JF296803,6/28/2022 2:20,001XX S CLINTON ST,1020,ARSON,BY FIRE,COMMERCIAL / BUSINESS OFFICE,False,False,...,34.0,28,9,1172750.0,1899684.0,2022,01-09-2024 15:40,41.880170,-87.641140,"(41.880169806, -87.641140205)"
44508,12815306,JF381829,09-03-2022 16:18,072XX S UNION AVE,1025,ARSON,AGGRAVATED,RESIDENCE,False,False,...,6.0,68,9,1173003.0,1856815.0,2022,01-03-2023 15:40,41.762528,-87.641479,"(41.762527673, -87.641478715)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32218,12589872,JF109871,01-11-2022 18:18,026XX E 76TH ST,143A,WEAPONS VIOLATION,UNLAWFUL POSSESSION - HANDGUN,DRIVEWAY - RESIDENTIAL,True,False,...,7.0,43,15,1194999.0,1855076.0,2022,01-03-2023 15:40,41.757242,-87.560919,"(41.757241977, -87.560918572)"
6506,12599996,JF122055,1/23/2022 18:30,023XX N MOODY AVE,1477,WEAPONS VIOLATION,RECKLESS FIREARM DISCHARGE,RESIDENCE - GARAGE,False,False,...,36.0,19,15,1135017.0,1914944.0,2022,01-03-2023 15:40,41.922797,-87.779331,"(41.922796719, -87.779331124)"
41520,12660271,JF195421,04-03-2022 04:07,071XX S EXCHANGE AVE,1477,WEAPONS VIOLATION,RECKLESS FIREARM DISCHARGE,OTHER (SPECIFY),False,False,...,7.0,43,15,1193651.0,1857944.0,2022,01-03-2023 15:40,41.765145,-87.565765,"(41.765145093, -87.565764903)"
41630,12753517,JF308340,07-03-2022 00:55,015XX N WELLS ST,1477,WEAPONS VIOLATION,RECKLESS FIREARM DISCHARGE,BAR OR TAVERN,False,False,...,27.0,8,15,1174423.0,1910541.0,2022,01-03-2023 15:40,41.909925,-87.634673,"(41.909924812, -87.634672572)"
33846,12783650,JF344431,08-03-2022 05:30,081XX S WESTERN AVE,143A,WEAPONS VIOLATION,UNLAWFUL POSSESSION - HANDGUN,MEDICAL / DENTAL OFFICE,False,False,...,18.0,70,15,1161788.0,1850707.0,2022,01-03-2023 15:40,41.746007,-87.682753,"(41.746006585, -87.682752791)"