### The nsmallest and nlargest methods
* The **nlargest** method returns a specified number of rows with the largest values from a given column.
* The **nsmallest** method returns rows with the smallest values from a given column.
* The **nlargest** and **nsmallest** methods are more efficient than sorting the entire **DataFrame**.

In [1]:
import pandas as pd

In [2]:
dataframe = pd.read_csv("../Crime Prediction in Chicago_Dataset.csv", index_col="ID").sort_index()

In [3]:
dataframe.head()

,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
ID,,,,,,,,,,,,,,,,,,,,,
26595,JF130370,02-01-2022 07:15,009XX E 79TH ST,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,624,...,8.0,69,01A,1184039.0,1852826.0,2022,01-01-2024 15:40,41.751331,-87.601155,"(41.751330763, -87.601154923)"
26596,JF130370,02-01-2022 06:54,009XX E 79TH ST,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,624,...,8.0,69,01A,1184039.0,1852826.0,2022,01-01-2024 15:40,41.751331,-87.601155,"(41.751330763, -87.601154923)"
26630,JF154557,2/24/2022 12:05,097XX S HALSTED ST,110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,True,False,2223,...,21.0,73,01A,1172697.0,1840207.0,2022,03-02-2024 15:40,41.716960,-87.643088,"(41.716959853, -87.643088472)"
26667,JF183032,3/22/2022 22:29,019XX E 73RD PL,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,333,...,7.0,43,01A,1190632.0,1856624.0,2022,11-11-2023 15:40,41.761596,-87.576873,"(41.761596299, -87.576872789)"
26682,JF193651,04-01-2022 13:49,008XX N LECLAIRE AVE,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,1531,...,37.0,25,01A,1142204.0,1905065.0,2022,02-06-2024 15:41,41.895557,-87.753169,"(41.895557198, -87.753168867)"

In [8]:
# Retrieve the 4 Beat with the highest/largest box office gross
dataframe.sort_values("Beat", ascending=False).head(4)

,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
ID,,,,,,,,,,,,,,,,,,,,,
12763554,JF320550,7/17/2022 2:00,012XX N HAMLIN AVE,820,THEFT,$500 AND UNDER,VEHICLE NON-COMMERCIAL,False,False,2535,...,27.0,23,6,1150825.0,1907787.0,2022,01-03-2023 15:40,41.902862,-87.721434,"(41.902862305, -87.721434358)"
13475933,JH282116,2/20/2022 0:00,018XX N MONTICELLO AVE,1754,OFFENSE INVOLVING CHILDREN,AGGRAVATED SEXUAL ASSAULT OF CHILD BY FAMILY M...,RESIDENCE,False,True,2535,...,26.0,22,2,NaN,NaN,2022,5/29/2024 15:41,NaN,NaN,NaN
12598922,JF120532,1/22/2022 5:00,037XX W GRAND AVE,031A,ROBBERY,ARMED - HANDGUN,STREET,False,False,2535,...,27.0,23,3,1151154.0,1908094.0,2022,01-03-2023 15:40,41.903698,-87.720218,"(41.903698297, -87.720217812)"
12605582,JF129082,1/30/2022 20:59,039XX W DIVISION ST,2024,NARCOTICS,POSSESS - HEROIN (WHITE),GAS STATION,True,False,2535,...,37.0,23,18,1149691.0,1907712.0,2022,01-03-2023 15:40,41.902679,-87.725602,"(41.902678618, -87.725601735)"

In [12]:
dataframe.nlargest(n=4, columns="Beat")

,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
ID,,,,,,,,,,,,,,,,,,,,,
12581840,JF100105,01-01-2022 00:01,018XX N MONTICELLO AVE,1310,CRIMINAL DAMAGE,TO PROPERTY,APARTMENT,False,False,2535,...,1.0,22,14,1151754.0,1912020.0,2022,01-03-2023 15:40,41.914460,-87.717910,"(41.914459819, -87.717910388)"
12581857,JF100075,01-01-2022 01:00,015XX N HARDING AVE,560,ASSAULT,SIMPLE,APARTMENT,True,True,2535,...,26.0,23,08A,1149765.0,1909956.0,2022,01-03-2023 15:40,41.908835,-87.725271,"(41.908834937, -87.725271489)"
12581931,JF100178,01-01-2022 03:30,039XX W DIVISION ST,460,BATTERY,SIMPLE,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,2535,...,37.0,23,08B,1149691.0,1907712.0,2022,01-03-2023 15:40,41.902679,-87.725602,"(41.902678618, -87.725601735)"
12582826,JF101211,01-02-2022 11:35,037XX W NORTH AVE,1477,WEAPONS VIOLATION,RECKLESS FIREARM DISCHARGE,BRIDGE,False,False,2535,...,26.0,23,15,1150989.0,1910368.0,2022,01-03-2023 15:40,41.909942,-87.720764,"(41.909941605, -87.720764249)"

In [13]:
dataframe["Beat"].nlargest(4)

ID
12581840    2535
12581857    2535
12581931    2535
12582826    2535
Name: Beat, dtype: int64

In [14]:
dataframe.nsmallest(4, columns="Beat")

,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
ID,,,,,,,,,,,,,,,,,,,,,
12582254,JF100514,01-01-2022 11:36,0000X W RANDOLPH ST,486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,111,...,42.0,32,08B,1176102.0,1901284.0,2022,01-03-2023 15:40,41.884485,-87.628784,"(41.884485451, -87.628783943)"
12582674,JF100952,01-01-2022 13:57,002XX N MICHIGAN AVE,870,THEFT,POCKET-PICKING,HOTEL / MOTEL,False,False,111,...,42.0,32,6,1177257.0,1901911.0,2022,01-03-2023 15:40,41.886180,-87.624524,"(41.886179873, -87.624523664)"
12582678,JF100964,01-02-2022 02:05,001XX N STATE ST,320,ROBBERY,STRONG ARM - NO WEAPON,CTA PLATFORM,False,False,111,...,42.0,32,3,1176330.0,1901649.0,2022,01-03-2023 15:40,41.885482,-87.627936,"(41.885481891, -87.627935689)"
12583650,JF102181,01-03-2022 12:20,001XX N STATE ST,860,THEFT,RETAIL THEFT,SMALL RETAIL STORE,False,False,111,...,42.0,32,6,1176352.0,1900927.0,2022,01-03-2023 15:40,41.883500,-87.627877,"(41.883500187, -87.627876698)"

In [15]:
dataframe["Beat"].nsmallest(4)

ID
12582254    111
12582674    111
12582678    111
12583650    111
Name: Beat, dtype: int64