### Retrieve row by index label with loc accessor
* The **loc** accessor retrieves one or more rows by index label.
* Provide a pair of square brackets after the accessor.

In [2]:
import pandas as pd

In [3]:
dataframe = pd.read_csv("../Crime Prediction in Chicago_Dataset.csv")

In [6]:
dataframe = dataframe.set_index('ID')

In [8]:
dataframe.loc[12592454]

Case Number                                   JF113025
Date                                   1/14/2022 15:55
Block                                067XX S MORGAN ST
IUCR                                              2826
Primary Type                             OTHER OFFENSE
Description             HARASSMENT BY ELECTRONIC MEANS
Location Description                         RESIDENCE
Arrest                                           False
Domestic                                          True
Beat                                               724
District                                             7
Ward                                              16.0
Community Area                                      68
FBI Code                                            26
X Coordinate                                 1170805.0
Y Coordinate                                 1860170.0
Year                                              2022
Updated On                             9/14/2023 15:41
Latitude                                     41.771782
Longitude                                   -87.649437
Location                 (41.771782439, -87.649436929)
Name: 12592454, dtype: object

In [11]:
dataframe.loc[[12592454, 12785595]]
dataframe.loc[[12785595, 12592454]]

,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
ID,,,,,,,,,,,,,,,,,,,,,
12785595,JF346553,08-05-2022 21:00,072XX S UNIVERSITY AVE,1544,SEX OFFENSE,SEXUAL EXPLOITATION OF A CHILD,APARTMENT,True,False,324,...,5.0,69,17,1185135.0,1857211.0,2022,9/14/2023 15:41,41.763338,-87.597001,"(41.763337967, -87.597001131)"
12592454,JF113025,1/14/2022 15:55,067XX S MORGAN ST,2826,OTHER OFFENSE,HARASSMENT BY ELECTRONIC MEANS,RESIDENCE,False,True,724,...,16.0,68,26,1170805.0,1860170.0,2022,9/14/2023 15:41,41.771782,-87.649437,"(41.771782439, -87.649436929)"

In [13]:
dataframe.loc[12592454: 12888104]

,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
ID,,,,,,,,,,,,,,,,,,,,,
12592454,JF113025,1/14/2022 15:55,067XX S MORGAN ST,2826,OTHER OFFENSE,HARASSMENT BY ELECTRONIC MEANS,RESIDENCE,False,True,724,...,16.0,68,26,1170805.0,1860170.0,2022,9/14/2023 15:41,41.771782,-87.649437,"(41.771782439, -87.649436929)"
12785595,JF346553,08-05-2022 21:00,072XX S UNIVERSITY AVE,1544,SEX OFFENSE,SEXUAL EXPLOITATION OF A CHILD,APARTMENT,True,False,324,...,5.0,69,17,1185135.0,1857211.0,2022,9/14/2023 15:41,41.763338,-87.597001,"(41.763337967, -87.597001131)"
12808281,JF373517,8/14/2022 14:00,055XX W ARDMORE AVE,1562,SEX OFFENSE,AGGRAVATED CRIMINAL SEXUAL ABUSE,RESIDENCE,False,False,1621,...,39.0,11,17,1138383.0,1937953.0,2022,9/14/2023 15:41,41.985875,-87.766404,"(41.985875279, -87.766403857)"
12888104,JF469015,11-10-2022 03:47,072XX S MAY ST,1477,WEAPONS VIOLATION,RECKLESS FIREARM DISCHARGE,STREET,False,False,733,...,17.0,68,15,1169903.0,1856822.0,2022,9/14/2023 15:41,41.762615,-87.652840,"(41.76261474, -87.652840463)"

In [16]:
# If the index position is in reverse, it won't give any result
dataframe.loc[12888104: 12592454]

Empty DataFrame
Columns: [Case Number, Date, Block, IUCR, Primary Type, Description, Location Description, Arrest, Domestic, Beat, District, Ward, Community Area, FBI Code, X Coordinate, Y Coordinate, Year, Updated On, Latitude, Longitude, Location]
Index: []

[0 rows x 21 columns]

In [19]:
dataframe.loc[12827191:]

,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
ID,,,,,,,,,,,,,,,,,,,,,
12827191,JF395031,9/13/2022 20:32,025XX W 72ND ST,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,True,832,...,18.0,66,14,1160781.0,1856827.0,2022,01-03-2023 15:40,41.762822,-87.686274,"(41.762821622, -87.686274014)"
12776992,JF336641,7/29/2022 19:30,081XX S COLFAX AVE,498,BATTERY,"AGG. DOMESTIC BATTERY - HANDS, FISTS, FEET, SE...",STREET,False,True,422,...,7.0,46,04B,1194924.0,1851513.0,2022,01-03-2023 15:40,41.747467,-87.561311,"(41.747466676, -87.561310599)"

In [20]:
dataframe.loc[:12888104]

,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
ID,,,,,,,,,,,,,,,,,,,,,
12592454,JF113025,1/14/2022 15:55,067XX S MORGAN ST,2826,OTHER OFFENSE,HARASSMENT BY ELECTRONIC MEANS,RESIDENCE,False,True,724,...,16.0,68,26,1170805.0,1860170.0,2022,9/14/2023 15:41,41.771782,-87.649437,"(41.771782439, -87.649436929)"
12785595,JF346553,08-05-2022 21:00,072XX S UNIVERSITY AVE,1544,SEX OFFENSE,SEXUAL EXPLOITATION OF A CHILD,APARTMENT,True,False,324,...,5.0,69,17,1185135.0,1857211.0,2022,9/14/2023 15:41,41.763338,-87.597001,"(41.763337967, -87.597001131)"
12808281,JF373517,8/14/2022 14:00,055XX W ARDMORE AVE,1562,SEX OFFENSE,AGGRAVATED CRIMINAL SEXUAL ABUSE,RESIDENCE,False,False,1621,...,39.0,11,17,1138383.0,1937953.0,2022,9/14/2023 15:41,41.985875,-87.766404,"(41.985875279, -87.766403857)"
12888104,JF469015,11-10-2022 03:47,072XX S MAY ST,1477,WEAPONS VIOLATION,RECKLESS FIREARM DISCHARGE,STREET,False,False,733,...,17.0,68,15,1169903.0,1856822.0,2022,9/14/2023 15:41,41.762615,-87.652840,"(41.76261474, -87.652840463)"