### Filtering with the where method
* Similar to square bracket or **loc**, the **where** method filters the original **DataFrame** with a Boolean Series.
* Pandas will populate rows that do not match the criteria with **NaN** values.
* Leaving in the **NaN** values can be advantageous for certain merge and visualization operations.

In [9]:
import pandas as pd

In [10]:
dataframe = pd.read_csv("../Crime Prediction in Chicago_Dataset.csv", index_col="ID").sort_index()

In [11]:
dataframe.head()

,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
ID,,,,,,,,,,,,,,,,,,,,,
26595,JF130370,02-01-2022 07:15,009XX E 79TH ST,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,624,...,8.0,69,01A,1184039.0,1852826.0,2022,01-01-2024 15:40,41.751331,-87.601155,"(41.751330763, -87.601154923)"
26596,JF130370,02-01-2022 06:54,009XX E 79TH ST,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,624,...,8.0,69,01A,1184039.0,1852826.0,2022,01-01-2024 15:40,41.751331,-87.601155,"(41.751330763, -87.601154923)"
26630,JF154557,2/24/2022 12:05,097XX S HALSTED ST,110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,True,False,2223,...,21.0,73,01A,1172697.0,1840207.0,2022,03-02-2024 15:40,41.716960,-87.643088,"(41.716959853, -87.643088472)"
26667,JF183032,3/22/2022 22:29,019XX E 73RD PL,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,333,...,7.0,43,01A,1190632.0,1856624.0,2022,11-11-2023 15:40,41.761596,-87.576873,"(41.761596299, -87.576872789)"
26682,JF193651,04-01-2022 13:49,008XX N LECLAIRE AVE,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,1531,...,37.0,25,01A,1142204.0,1905065.0,2022,02-06-2024 15:41,41.895557,-87.753169,"(41.895557198, -87.753168867)"

In [12]:
is_homicide = dataframe["Primary Type"] == "HOMICIDE"
dataframe[is_homicide]
dataframe.loc[is_homicide]
dataframe.where(is_homicide)

,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
ID,,,,,,,,,,,,,,,,,,,,,
26595,JF130370,02-01-2022 07:15,009XX E 79TH ST,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,624.0,...,8.0,69.0,01A,1184039.0,1852826.0,2022.0,01-01-2024 15:40,41.751331,-87.601155,"(41.751330763, -87.601154923)"
26596,JF130370,02-01-2022 06:54,009XX E 79TH ST,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,624.0,...,8.0,69.0,01A,1184039.0,1852826.0,2022.0,01-01-2024 15:40,41.751331,-87.601155,"(41.751330763, -87.601154923)"
26630,JF154557,2/24/2022 12:05,097XX S HALSTED ST,110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,True,False,2223.0,...,21.0,73.0,01A,1172697.0,1840207.0,2022.0,03-02-2024 15:40,41.716960,-87.643088,"(41.716959853, -87.643088472)"
26667,JF183032,3/22/2022 22:29,019XX E 73RD PL,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,333.0,...,7.0,43.0,01A,1190632.0,1856624.0,2022.0,11-11-2023 15:40,41.761596,-87.576873,"(41.761596299, -87.576872789)"
26682,JF193651,04-01-2022 13:49,008XX N LECLAIRE AVE,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,1531.0,...,37.0,25.0,01A,1142204.0,1905065.0,2022.0,02-06-2024 15:41,41.895557,-87.753169,"(41.895557198, -87.753168867)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13627481,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13627576,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13627896,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13629868,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13630511,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN