### Methods on Index and Columns
* Use the **index** and **columns** attributes to access the **DataFrame** index/column labels.
* These objects support string methods via their own **str** attribute.

In [13]:
import pandas as pd

In [14]:
dataframe = pd.read_csv("../Crime Prediction in Chicago_Dataset.csv", index_col="ID").sort_index()

In [15]:
dataframe.head()

,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
ID,,,,,,,,,,,,,,,,,,,,,
26595,JF130370,02-01-2022 07:15,009XX E 79TH ST,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,624,...,8.0,69,01A,1184039.0,1852826.0,2022,01-01-2024 15:40,41.751331,-87.601155,"(41.751330763, -87.601154923)"
26596,JF130370,02-01-2022 06:54,009XX E 79TH ST,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,624,...,8.0,69,01A,1184039.0,1852826.0,2022,01-01-2024 15:40,41.751331,-87.601155,"(41.751330763, -87.601154923)"
26630,JF154557,2/24/2022 12:05,097XX S HALSTED ST,110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,True,False,2223,...,21.0,73,01A,1172697.0,1840207.0,2022,03-02-2024 15:40,41.716960,-87.643088,"(41.716959853, -87.643088472)"
26667,JF183032,3/22/2022 22:29,019XX E 73RD PL,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,333,...,7.0,43,01A,1190632.0,1856624.0,2022,11-11-2023 15:40,41.761596,-87.576873,"(41.761596299, -87.576872789)"
26682,JF193651,04-01-2022 13:49,008XX N LECLAIRE AVE,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,1531,...,37.0,25,01A,1142204.0,1905065.0,2022,02-06-2024 15:41,41.895557,-87.753169,"(41.895557198, -87.753168867)"

In [16]:
dataframe.index = dataframe.index + 1

In [17]:
dataframe.head()

,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
ID,,,,,,,,,,,,,,,,,,,,,
26596,JF130370,02-01-2022 07:15,009XX E 79TH ST,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,624,...,8.0,69,01A,1184039.0,1852826.0,2022,01-01-2024 15:40,41.751331,-87.601155,"(41.751330763, -87.601154923)"
26597,JF130370,02-01-2022 06:54,009XX E 79TH ST,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,624,...,8.0,69,01A,1184039.0,1852826.0,2022,01-01-2024 15:40,41.751331,-87.601155,"(41.751330763, -87.601154923)"
26631,JF154557,2/24/2022 12:05,097XX S HALSTED ST,110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,True,False,2223,...,21.0,73,01A,1172697.0,1840207.0,2022,03-02-2024 15:40,41.716960,-87.643088,"(41.716959853, -87.643088472)"
26668,JF183032,3/22/2022 22:29,019XX E 73RD PL,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,333,...,7.0,43,01A,1190632.0,1856624.0,2022,11-11-2023 15:40,41.761596,-87.576873,"(41.761596299, -87.576872789)"
26683,JF193651,04-01-2022 13:49,008XX N LECLAIRE AVE,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,1531,...,37.0,25,01A,1142204.0,1905065.0,2022,02-06-2024 15:41,41.895557,-87.753169,"(41.895557198, -87.753168867)"

In [18]:
dataframe.columns = dataframe.columns.str.lower()

In [19]:
dataframe.head()

,case number,date,block,iucr,primary type,description,location description,arrest,domestic,beat,...,ward,community area,fbi code,x coordinate,y coordinate,year,updated on,latitude,longitude,location
ID,,,,,,,,,,,,,,,,,,,,,
26596,JF130370,02-01-2022 07:15,009XX E 79TH ST,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,624,...,8.0,69,01A,1184039.0,1852826.0,2022,01-01-2024 15:40,41.751331,-87.601155,"(41.751330763, -87.601154923)"
26597,JF130370,02-01-2022 06:54,009XX E 79TH ST,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,624,...,8.0,69,01A,1184039.0,1852826.0,2022,01-01-2024 15:40,41.751331,-87.601155,"(41.751330763, -87.601154923)"
26631,JF154557,2/24/2022 12:05,097XX S HALSTED ST,110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,True,False,2223,...,21.0,73,01A,1172697.0,1840207.0,2022,03-02-2024 15:40,41.716960,-87.643088,"(41.716959853, -87.643088472)"
26668,JF183032,3/22/2022 22:29,019XX E 73RD PL,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,333,...,7.0,43,01A,1190632.0,1856624.0,2022,11-11-2023 15:40,41.761596,-87.576873,"(41.761596299, -87.576872789)"
26683,JF193651,04-01-2022 13:49,008XX N LECLAIRE AVE,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,1531,...,37.0,25,01A,1142204.0,1905065.0,2022,02-06-2024 15:41,41.895557,-87.753169,"(41.895557198, -87.753168867)"